[env]
_.file = '.env' # https://mise.jdx.dev/environments/#env-file
UV_PYTHON = { value = "",  tools = true } # https://github.com/jdx/mise/discussions/4698

[settings]
python.uv_venv_auto = true # https://mise.jdx.dev/lang/python.html#python.uv_venv_auto
experimental = true

[tasks.check]
alias = "c"
description = "Run static code analysis and type checking"
run = [
  'uv run ruff check --fix',
  'uv run ruff format',
  'uv run ty check'
]

[tasks.marimo]
alias = "m"
description = "Run marimo"
run = [
  'uv run marimo edit'
]

[tasks.sync]
alias = "s"
description = "Install dependencies"
run = [
  'uv sync'
]
