[env]
_.file = { path = '.env', tools = true } # https://mise.jdx.dev/environments/#env-file
_.python.venv = { path = '.venv', create = true}       # https://mise.jdx.dev/lang/python.html
UV_PYTHON = { value = "", tools = true } # https://github.com/jdx/mise/discussions/4698
