[project]
name = "python-boilerplate"
version = "0.1.0"
description = "A Python boilerplate project."
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.11"
dependencies = [
  "marimo>=0.18.4"
]

[dependency-groups]
dev = [
  "ruff>=0.14.10",
  "ty>=0.0.8",
  "pytest>=8.0.0",
  "pytest-cov>=7.0.0",
  "sqlfluff>=4.0.4",
  "pre-commit>=4.0.0",
]
